spring:
  main:
    web-application-type: reactive
  application:
    name: chen-api-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yichen_api
    username: root
    password: 12345678
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          filters:
            - AddRequestHeader=xiaozhang, niubi
          predicates:
            - Path=/api/**
server:
  port: 8090
# application.yml (Spring Boot)

dubbo:
  application:
    name: dubbo-springboot-demo-consumer
    qos-port: 33333
  protocol:
    name: dubbo
    port: 22221
  registry:
    address: nacos://localhost:8848

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
