spring:
  application:
    name: chen-api-gateway
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          filters:
            - AddRequestHeader=xiaozhang, niubi
          predicates:
            - Path=/api/**
server:
  port: 8090
# application.yml (Spring Boot)

dubbo:
  application:
    name: dubbo-springboot-demo-consumer
    qos-port: 33333
  protocol:
    name: dubbo
    port: 22221
  registry:
    address: nacos://localhost:8848

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
